### ISSUE TITLE
Front end is blank

### ISSUE THREAD

**Issue by ryanpatrickmckenna** [feedernet/petnet-feeder-service#72]
Hello! Thank you for creating this project as it will be extremely helpful once I get it up and running.
I have read over the Wiki extensively and followed the all the steps except for creating my own DNS server.
I do not plan on using the mobile app and really only need to configure the feeder in a "set and forget" manner.
I do not mind accessing it just by IP address.

I only ran into a couple of snags during installation which were resolved by updating the docker packages with apt upgrade and adding my user to the docker group. All of the terminal commands listed in the Wiki run successfully now.

The issue now is when I attempt to navigate to the front end, I am met with a blank page.
You can see from my RaspberryPi here:
![image](https://user-images.githubusercontent.com/73675553/148127849-e6c30ab9-391f-42de-98bc-c7ebd77bd12f.png)
 After fiddling around with the URL, thinking I had missed something obvious like /home or /feeder I was met with a 504 error when trying to access it from my computer (instead of my RPI). This error persists even after a reboot of the RPI.
![image](https://user-images.githubusercontent.com/73675553/148128215-afdfd7b6-1000-4859-a673-8a9b3e71bcde.png)

Is it completely necessary to setup a DNS server for this project to function? Or is that for mere ease-of-access to make the mobile app work and make a vanity URL for a computer?

I have also attached my logs from docker in case that is useful.

I hope I haven't missed anything obvious or misunderstood the instructions. If I have please let me know, I am happy to learn.

Any help is appreciated. Thank you so much.

[logs.txt](https://github.com/feedernet/petnet-feeder-service/files/7810575/logs.txt)

**Comment by johndc7** [comment]
The DNS is a requirement and is only there to force the feeder to connect to feedernet instead of the petnet servers that no longer exist.

As far as the blank page, I would double check your nginx config. You should also be able to connect to the feedernet service directly at your raspberry pi's IP port 5000 (per your screenshots, http://192.168.1.21:5000). That would bypass nginx so you can see if that's the problem.

I just setup mine yesterday so maybe I'm missing something here but that's what I noticed with my experience with this so far. Just trying to help :)

**Comment by ryanpatrickmckenna** [comment]
@johndc7 Thank you! Including the port helped and I am able to see the front end. Not sure why it's not working otherwise or if that signals any problems I should be concerned about. I cannot use https either and I am not sure what part of the setup contains the HTTPS proxy.

**Comment by johndc7** [comment]
The https certs are generated by the feedernet service and used by nginx. If it loads from port 5000 then it sounds like the feedernet service is working.

You can also see that the certs have been generated properly in the log file you attached:
```
petnet-feeder-service    | 2022-01-04 21:23:30,385   WARNING  feeder: Generating self-signed key pair!
petnet-feeder-service    | 2022-01-04 21:23:33,063   INFO     feeder: Writing new public key to /data/pkey.pem
petnet-feeder-service    | 2022-01-04 21:23:33,064   INFO     feeder: Writing new private key to /data/cert.pem
```

I would check:
1.  Make sure `pkey.pem` and `cert.pem` actually exist under the data folder.
2. Check your nginx config file to make sure it looks like the one in the getting started page.

**Comment by ryanpatrickmckenna** [comment]
Merp. I have no idea why it's not working. My nginx config file and docker-compose yaml files look fine. The cert files are there. I'm assuming this has to do with my lack of knowledge of how DNS works. I think I need a SRV record to point it to the right port?  My A records are redirecting to my raspberry Pi just fine so I don't know what else it could be.

To clarify, My feeder will not connect to my server. I can get to my server just fine using the IP address and port or FQDN like this: http://api.arrowconnect.io:5000/ but I **have** to include the port number and use HTTP. If I don't include the port number or I use HTTPS, I get hella errors like 504 errors, connection closed, that blank page or any combination of that with "site isn't secured" messages. 

I think what I would like to know is if certificate errors are normal or if when this project is working properly, I should be able to use HTTPS without any errors at all. Because it would make a lot of sense if the feeder won't connect unless SSL is present.

**Comment by johndc7** [comment]
> I think I need a SRV record to point it to the right port?
No, the feeder will try to connect on port 443 (https). The reason for the A records is because it will try to connect to the petnet servers. You are changing the IP address so when it requests the petnet servers, it get's your feedernet server instead.

When you set this up, there are 2 different containers running in docker. One of them is the actual feedernet service (bound to port 5000) and the other is nginx (bound to port 80 and 443). All nginx is doing is forwarding the traffic to the feedernet service on port 5000. The `pem` files are generated by the feedernet service and stored in a shared folder where nginx can read them. This is only because nginx will not generate these files on it's own.

If you can access the feedernet service on port 5000 but not over https (443) it sounds like it would be an issue with the nginx container. The site isn't secured messages are normal since it's a self-signed cert (you don't own the domain arrowconnect.io so it's not possible for you to get a legit one). This doesn't really matter since the petnet feeder doesn't actually check if the cert is valid. It only requires that one is there since the petnet servers were over https. You should be able to continue to the site anyways.

**Comment by ryanpatrickmckenna** [comment]
@johndc7 Okay thank you. This info is very helpful. Honestly I think I might just re-image my raspberry pi and start the project from scratch. Thanks for your help!

**Comment by kruton** [comment]
It would be helpful to see the developers console output from your browser.

I have fixed quite a bit of problems from the Bootstrap 5 upgrade since your original report.

**Comment by ryanpatrickmckenna** [comment]
> It would be helpful to see the developers console output from your browser.
> 
> I have fixed quite a bit of problems from the Bootstrap 5 upgrade since your original report.

Awesome I will give it a shot thank you.

**Comment by ryanpatrickmckenna** [comment]
> 

Hi I installed everything on a fresh raspberry pi image. Can't get frontend up at all now and getting hella errors in the docker logs:

petnet-feeder-service    | Traceback (most recent call last):
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/bin/alembic", line 8, in <module>
petnet-feeder-service    |     sys.exit(main())
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 588, in main
petnet-feeder-service    |     CommandLine(prog=prog).main(argv=argv)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 582, in main
petnet-feeder-service    |     self.run_cmd(cfg, options)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 559, in run_cmd
petnet-feeder-service    |     fn(
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/command.py", line 320, in upgrade
petnet-feeder-service    |     script.run_env()
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/script/base.py", line 563, in run_env
petnet-feeder-service    |     util.load_python_file(self.dir, "env.py")
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
petnet-feeder-service    |     module = load_module_py(module_id, path)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
petnet-feeder-service    |     spec.loader.exec_module(module)  # type: ignore
petnet-feeder-service    |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
petnet-feeder-service    |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
petnet-feeder-service    |   File "feeder/database/alembic/env.py", line 8, in <module>
petnet-feeder-service    |     from feeder.database.session import metadata
petnet-feeder-service    |   File "/tmp/feeder/__init__.py", line 1, in <module>
petnet-feeder-service    |     from feeder.config import Settings
petnet-feeder-service    |   File "/tmp/feeder/config.py", line 1, in <module>
petnet-feeder-service    |     from pydantic import BaseSettings
petnet-feeder-service    | ImportError: Error loading shared library ld-linux-armhf.so.3: No such file or directory (needed by /root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/pydantic/__init__.cpython-39-arm-linux-gnueabihf.so)
petnet-feeder-service    | Traceback (most recent call last):
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/bin/alembic", line 8, in <module>
petnet-feeder-service    |     sys.exit(main())
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 588, in main
petnet-feeder-service    |     CommandLine(prog=prog).main(argv=argv)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 582, in main
petnet-feeder-service    |     self.run_cmd(cfg, options)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 559, in run_cmd
petnet-feeder-service    |     fn(
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/command.py", line 320, in upgrade
petnet-feeder-service    |     script.run_env()
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/script/base.py", line 563, in run_env
petnet-feeder-service    |     util.load_python_file(self.dir, "env.py")
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
petnet-feeder-service    |     module = load_module_py(module_id, path)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
petnet-feeder-service    |     spec.loader.exec_module(module)  # type: ignore
petnet-feeder-service    |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
petnet-feeder-service    |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
petnet-feeder-service    |   File "feeder/database/alembic/env.py", line 8, in <module>
petnet-feeder-service    |     from feeder.database.session import metadata
petnet-feeder-service    |   File "/tmp/feeder/__init__.py", line 1, in <module>
petnet-feeder-service    |     from feeder.config import Settings
petnet-feeder-service    |   File "/tmp/feeder/config.py", line 1, in <module>
petnet-feeder-service    |     from pydantic import BaseSettings
petnet-feeder-service    | ImportError: Error loading shared library ld-linux-armhf.so.3: No such file or directory (needed by /root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/pydantic/__init__.cpython-39-arm-linux-gnueabihf.so)
petnet-feeder-service    | Traceback (most recent call last):
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/bin/alembic", line 8, in <module>
petnet-feeder-service    |     sys.exit(main())
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 588, in main
petnet-feeder-service    |     CommandLine(prog=prog).main(argv=argv)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 582, in main
petnet-feeder-service    |     self.run_cmd(cfg, options)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 559, in run_cmd
petnet-feeder-service    |     fn(
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/command.py", line 320, in upgrade
petnet-feeder-service    |     script.run_env()
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/script/base.py", line 563, in run_env
petnet-feeder-service    |     util.load_python_file(self.dir, "env.py")
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
petnet-feeder-service    |     module = load_module_py(module_id, path)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
petnet-feeder-service    |     spec.loader.exec_module(module)  # type: ignore
petnet-feeder-service    |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
petnet-feeder-service    |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
petnet-feeder-service    |   File "feeder/database/alembic/env.py", line 8, in <module>
petnet-feeder-service    |     from feeder.database.session import metadata
petnet-feeder-service    |   File "/tmp/feeder/__init__.py", line 1, in <module>
petnet-feeder-service    |     from feeder.config import Settings
petnet-feeder-service    |   File "/tmp/feeder/config.py", line 1, in <module>
petnet-feeder-service    |     from pydantic import BaseSettings
petnet-feeder-service    | ImportError: Error loading shared library ld-linux-armhf.so.3: No such file or directory (needed by /root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/pydantic/__init__.cpython-39-arm-linux-gnueabihf.so)
petnet-feeder-service    | Traceback (most recent call last):
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/bin/alembic", line 8, in <module>
petnet-feeder-service    |     sys.exit(main())
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 588, in main
petnet-feeder-service    |     CommandLine(prog=prog).main(argv=argv)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 582, in main
petnet-feeder-service    |     self.run_cmd(cfg, options)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 559, in run_cmd
petnet-feeder-service    |     fn(
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/command.py", line 320, in upgrade
petnet-feeder-service    |     script.run_env()
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/script/base.py", line 563, in run_env
petnet-feeder-service    |     util.load_python_file(self.dir, "env.py")
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
petnet-feeder-service    |     module = load_module_py(module_id, path)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
petnet-feeder-service    |     spec.loader.exec_module(module)  # type: ignore
petnet-feeder-service    |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
petnet-feeder-service    |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
petnet-feeder-service    |   File "feeder/database/alembic/env.py", line 8, in <module>
petnet-feeder-service    |     from feeder.database.session import metadata
petnet-feeder-service    |   File "/tmp/feeder/__init__.py", line 1, in <module>
petnet-feeder-service    |     from feeder.config import Settings
petnet-feeder-service    |   File "/tmp/feeder/config.py", line 1, in <module>
petnet-feeder-service    |     from pydantic import BaseSettings
petnet-feeder-service    | ImportError: Error loading shared library ld-linux-armhf.so.3: No such file or directory (needed by /root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/pydantic/__init__.cpython-39-arm-linux-gnueabihf.so)
petnet-feeder-service    | Traceback (most recent call last):
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/bin/alembic", line 8, in <module>
petnet-feeder-service    |     sys.exit(main())
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 588, in main
petnet-feeder-service    |     CommandLine(prog=prog).main(argv=argv)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 582, in main
petnet-feeder-service    |     self.run_cmd(cfg, options)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 559, in run_cmd
petnet-feeder-service    |     fn(
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/command.py", line 320, in upgrade
petnet-feeder-service    |     script.run_env()
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/script/base.py", line 563, in run_env
petnet-feeder-service    |     util.load_python_file(self.dir, "env.py")
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
petnet-feeder-service    |     module = load_module_py(module_id, path)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
petnet-feeder-service    |     spec.loader.exec_module(module)  # type: ignore
petnet-feeder-service    |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
petnet-feeder-service    |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
petnet-feeder-service    |   File "feeder/database/alembic/env.py", line 8, in <module>
petnet-feeder-service    |     from feeder.database.session import metadata
petnet-feeder-service    |   File "/tmp/feeder/__init__.py", line 1, in <module>
petnet-feeder-service    |     from feeder.config import Settings
petnet-feeder-service    |   File "/tmp/feeder/config.py", line 1, in <module>
petnet-feeder-service    |     from pydantic import BaseSettings
petnet-feeder-service    | ImportError: Error loading shared library ld-linux-armhf.so.3: No such file or directory (needed by /root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/pydantic/__init__.cpython-39-arm-linux-gnueabihf.so)
petnet-feeder-service    | Traceback (most recent call last):
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/bin/alembic", line 8, in <module>
petnet-feeder-service    |     sys.exit(main())
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 588, in main
petnet-feeder-service    |     CommandLine(prog=prog).main(argv=argv)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 582, in main
petnet-feeder-service    |     self.run_cmd(cfg, options)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 559, in run_cmd
petnet-feeder-service    |     fn(
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/command.py", line 320, in upgrade
petnet-feeder-service    |     script.run_env()
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/script/base.py", line 563, in run_env
petnet-feeder-service    |     util.load_python_file(self.dir, "env.py")
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
petnet-feeder-service    |     module = load_module_py(module_id, path)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
petnet-feeder-service    |     spec.loader.exec_module(module)  # type: ignore
petnet-feeder-service    |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
petnet-feeder-service    |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
petnet-feeder-service    |   File "feeder/database/alembic/env.py", line 8, in <module>
petnet-feeder-service    |     from feeder.database.session import metadata
petnet-feeder-service    |   File "/tmp/feeder/__init__.py", line 1, in <module>
petnet-feeder-service    |     from feeder.config import Settings
petnet-feeder-service    |   File "/tmp/feeder/config.py", line 1, in <module>
petnet-feeder-service    |     from pydantic import BaseSettings
petnet-feeder-service    | ImportError: Error loading shared library ld-linux-armhf.so.3: No such file or directory (needed by /root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/pydantic/__init__.cpython-39-arm-linux-gnueabihf.so)
petnet-feeder-service    | Traceback (most recent call last):
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/bin/alembic", line 8, in <module>
petnet-feeder-service    |     sys.exit(main())
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 588, in main
petnet-feeder-service    |     CommandLine(prog=prog).main(argv=argv)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 582, in main
petnet-feeder-service    |     self.run_cmd(cfg, options)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 559, in run_cmd
petnet-feeder-service    |     fn(
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/command.py", line 320, in upgrade
petnet-feeder-service    |     script.run_env()
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/script/base.py", line 563, in run_env
petnet-feeder-service    |     util.load_python_file(self.dir, "env.py")
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
petnet-feeder-service    |     module = load_module_py(module_id, path)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
petnet-feeder-service    |     spec.loader.exec_module(module)  # type: ignore
petnet-feeder-service    |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
petnet-feeder-service    |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
petnet-feeder-service    |   File "feeder/database/alembic/env.py", line 8, in <module>
petnet-feeder-service    |     from feeder.database.session import metadata
petnet-feeder-service    |   File "/tmp/feeder/__init__.py", line 1, in <module>
petnet-feeder-service    |     from feeder.config import Settings
petnet-feeder-service    |   File "/tmp/feeder/config.py", line 1, in <module>
petnet-feeder-service    |     from pydantic import BaseSettings
petnet-feeder-service    | ImportError: Error loading shared library ld-linux-armhf.so.3: No such file or directory (needed by /root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/pydantic/__init__.cpython-39-arm-linux-gnueabihf.so)
petnet-feeder-service    | Traceback (most recent call last):
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/bin/alembic", line 8, in <module>
petnet-feeder-service    |     sys.exit(main())
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 588, in main
petnet-feeder-service    |     CommandLine(prog=prog).main(argv=argv)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 582, in main
petnet-feeder-service    |     self.run_cmd(cfg, options)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 559, in run_cmd
petnet-feeder-service    |     fn(
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/command.py", line 320, in upgrade
petnet-feeder-service    |     script.run_env()
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/script/base.py", line 563, in run_env
petnet-feeder-service    |     util.load_python_file(self.dir, "env.py")
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
petnet-feeder-service    |     module = load_module_py(module_id, path)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
petnet-feeder-service    |     spec.loader.exec_module(module)  # type: ignore
petnet-feeder-service    |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
petnet-feeder-service    |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
petnet-feeder-service    |   File "feeder/database/alembic/env.py", line 8, in <module>
petnet-feeder-service    |     from feeder.database.session import metadata
petnet-feeder-service    |   File "/tmp/feeder/__init__.py", line 1, in <module>
petnet-feeder-service    |     from feeder.config import Settings
petnet-feeder-service    |   File "/tmp/feeder/config.py", line 1, in <module>
petnet-feeder-service    |     from pydantic import BaseSettings
petnet-feeder-service    | ImportError: Error loading shared library ld-linux-armhf.so.3: No such file or directory (needed by /root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/pydantic/__init__.cpython-39-arm-linux-gnueabihf.so)
petnet-feeder-service    | Traceback (most recent call last):
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/bin/alembic", line 8, in <module>
petnet-feeder-service    |     sys.exit(main())
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 588, in main
petnet-feeder-service    |     CommandLine(prog=prog).main(argv=argv)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 582, in main
petnet-feeder-service    |     self.run_cmd(cfg, options)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/config.py", line 559, in run_cmd
petnet-feeder-service    |     fn(
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/command.py", line 320, in upgrade
petnet-feeder-service    |     script.run_env()
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/script/base.py", line 563, in run_env
petnet-feeder-service    |     util.load_python_file(self.dir, "env.py")
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
petnet-feeder-service    |     module = load_module_py(module_id, path)
petnet-feeder-service    |   File "/root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
petnet-feeder-service    |     spec.loader.exec_module(module)  # type: ignore
petnet-feeder-service    |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
petnet-feeder-service    |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
petnet-feeder-service    |   File "feeder/database/alembic/env.py", line 8, in <module>
petnet-feeder-service    |     from feeder.database.session import metadata
petnet-feeder-service    |   File "/tmp/feeder/__init__.py", line 1, in <module>
petnet-feeder-service    |     from feeder.config import Settings
petnet-feeder-service    |   File "/tmp/feeder/config.py", line 1, in <module>
petnet-feeder-service    |     from pydantic import BaseSettings
petnet-feeder-service    | ImportError: Error loading shared library ld-linux-armhf.so.3: No such file or directory (needed by /root/.cache/pypoetry/virtualenvs/feedernet-6WcazSRI-py3.9/lib/python3.9/site-packages/pydantic/__init__.cpython-39-arm-linux-gnueabihf.so)
